import Image from 'next/image';
import Link from 'next/link';
import { Hero } from '@/components/hero';
import { WorkRail } from '@/components/work-rail';
import { ContactCTA,Footer,JsonLd,TextLink } from '@/components/common';
import { Arrow } from '@/components/icons';
import { metadata,person,site } from '@/lib/site';
export const generateMetadata = () => metadata('Mayank Harsh — Creative Director & Social Media Strategist','Mayank Harsh’s creative portfolio: art, literature, music and cultural storytelling, with selected creator work and social media strategy.','/');
export default function Home(){return <><main id="main" className="viewport"><Hero/>
 <section id="selected-work" className="section selected-work"><div className="section-heading"><div><p className="eyebrow">01 / Selected work</p><h2>Stories worth<br/><em>stopping for.</em></h2></div><div className="section-aside"><p>Art, literature and emotion, expressed through the language of social.</p><TextLink href="/work">Explore the archive</TextLink></div></div><WorkRail/></section>
 <section className="section featured"><div className="feature-art"><Image src="/media/CrodTefqiKm.jpg" alt="The Starry Night, featured in Mayank’s creator work" width={600} height={900} unoptimized/><span>Personal creator work / @sl6dl7</span></div><div className="feature-copy"><p className="eyebrow">02 / A closer look</p><h2>A visual world<br/>for <em>words.</em></h2><p>Art, poetry and literature become a shared visual language. A look inside the creator work associated with @sl6dl7.</p><div className="feature-result"><strong>9.5M</strong><p>Views recorded for a featured Reel<br/><span>Published founder result · source inside</span></p></div><TextLink href="/work/sl6dl7">Read the case study</TextLink></div></section>
 <section className="section practice"><p className="eyebrow">03 / The creative practice</p><div className="practice-layout"><h2>Culture is the starting point.<br/><span>Emotion is the connection.</span></h2><div><p>I&apos;m Mayank Harsh, a creative director and social media strategist. My work brings together art, literature, poetry, music and social storytelling.</p><p>My creator practice includes @sl6dl7 and @shehzada.says. I&apos;m also the founder and creative director of Project Monet.</p><TextLink href="/about">More about me</TextLink></div></div></section>
 <section className="section expertise"><p className="eyebrow">04 / Ways of thinking</p><Link className="expertise-row" href="/expertise/creative-direction"><span>01</span><div><h2>Creative direction</h2><p>Concept, narrative, image and motion. One coherent point of view.</p></div><Arrow diagonal/></Link><Link className="expertise-row" href="/expertise/social-media-strategy"><span>02</span><div><h2>Social media strategy</h2><p>Positioning, formats and content systems with a reason behind them.</p></div><Arrow diagonal/></Link></section>
 <section className="section agency-section"><p className="eyebrow">05 / Founder context</p><div><h2>A personal practice.<br/>An agency called <em>Project Monet.</em></h2><p>Project Monet is the separate agency I founded and creatively direct. This site is where my personal work and thinking live.</p><TextLink href="/project-monet">The connection</TextLink></div></section>
 <ContactCTA/><JsonLd data={{'@context':'https://schema.org','@graph':[person,{'@type':'WebSite','@id':site.url+'/#website',url:site.url,name:site.name,publisher:{'@id':site.url+'/#person'}}]}}/>
 </main><Footer/></>;}
