import Image from 'next/image';
import { Breadcrumbs,ContactCTA,JsonLd,PageIntro,PageShell,TextLink } from '@/components/common';
import { metadata,person,site } from '@/lib/site';
import { evidenceDate,evidenceUrl,work } from '@/lib/work';
export const generateMetadata=()=>({...metadata('@sl6dl7 — Art, Literature & Social Storytelling','A documented look at Mayank Harsh’s @sl6dl7 creator work, with six original Reel links, selected visuals and published founder results.','/work/sl6dl7'),openGraph:{title:'@sl6dl7 — Art, Literature & Social Storytelling',description:'Selected creator work by Mayank Harsh, with original Reel links and published founder results.',url:site.url+'/work/sl6dl7',type:'article',images:[{url:site.url+work[3].image,width:320,height:569}]},twitter:{card:'summary_large_image' as const,title:'@sl6dl7 — Art, Literature & Social Storytelling',description:'Selected creator work by Mayank Harsh.',images:[site.url+work[3].image]}});
export default function CaseStudy(){return <PageShell><Breadcrumbs items={[{label:'Work',path:'/work'},{label:'@sl6dl7',path:'/work/sl6dl7'}]}/><PageIntro label="Creator collection / @sl6dl7" title="A visual world for words."><p>Art, poetry and literature meet cinematic imagery in Mayank Harsh&apos;s personal creator practice. This collection documents selected Reels and their published results.</p></PageIntro><div className="case-banner"><Image src={work[3].image} alt={work[3].alt} width={960} height={600} unoptimized priority/><div><p className="eyebrow">The practice</p><h2>Art.<br/>Literature.<br/><em>Emotion.</em></h2></div></div><div className="case-facts"><div><span>Account</span><strong>@sl6dl7</strong></div><div><span>Role</span><strong>Creator / Creative director</strong></div><div><span>Work type</span><strong>Personal creator work</strong></div><div><span>Evidence reviewed</span><strong>25 September 2026</strong></div></div>
 <div className="case-body"><aside><p className="eyebrow">Inside the work</p><a href="#context">Context & role</a><a href="#concept">Insight & concept</a><a href="#execution">Execution</a><a href="#results">Results & evidence</a><a href="#learning">What can be learned</a></aside><div className="prose">
 <section id="context"><h2>Context & role</h2><p>@sl6dl7 is a creator identity associated with Mayank Harsh. Its selected work sits at the intersection of art, literature, poetry and emotional storytelling.</p><p>Mayank is identified as founder and creative director in Project Monet&apos;s public creator proof. The work here belongs to his personal creator practice; the figures are not agency client results.</p></section>
 <section id="concept"><h2>Insight & concept</h2><p>The selection offers a useful way to read the visual direction: begin with a feeling, then give it an image. A portrait, a painting, a staircase or an open book establishes atmosphere before a viewer has read a caption.</p><p>Across these covers, subdued colours, tactile details and familiar cultural references create a recognisable editorial world. This is a reading of the visible work, not a claim that a particular choice caused its reach.</p></section>
 <section id="execution"><h2>Execution</h2><p>The work is published as Instagram Reels. The six covers below show the range within the collection, from cinematic portraiture to literary imagery and painting.</p><p>Open each original Reel to experience its complete edit, audio and caption. The portfolio preserves the published covers and links directly to the source instead of automatically playing multiple videos.</p></section>
 <section id="results"><h2>Results & evidence</h2><p>The featured Reel is publicly recorded at <strong>9.5 million views and 685,000 likes</strong> in Project Monet&apos;s founder proof. Other selected Reels have recorded view counts from 2.5 million to 4.2 million.</p><p>These are published snapshots reviewed on 25 September 2026, not live Instagram analytics. They describe individual content results and do not establish sales, revenue or the cause of the reach.</p><TextLink href={evidenceUrl} external>View the published founder proof</TextLink></section>
 <section id="learning"><h2>What can be learned</h2><p>A coherent portfolio does not require every piece to look identical. Here, varied subjects still share a quiet, literary sensibility. That consistency is useful to study when building a body of social content.</p><p>The next question is qualitative as well as numerical: what feeling carries from the first frame through the complete Reel? The source links make that reading possible without reducing the work to a count.</p></section></div></div>
 <section className="case-reels"><div className="section-heading"><div><p className="eyebrow">Original work / Recorded results</p><h2>The selected Reels.</h2></div><p>Source snapshot: {evidenceDate}<br/>Personal creator results</p></div><div className="work-grid">{work.map(item=><article key={item.id} id={`reel-${item.id}`} className="work-card"><a href={item.href} target="_blank" rel="noopener noreferrer" className="work-image" aria-label={`Watch ${item.title} on Instagram (opens in new tab)`}><Image src={item.image} alt={item.alt} width={320} height={569} unoptimized/><span className="work-open">↗</span></a><div className="work-caption"><h3>{item.title}</h3><p>{item.views} views · {item.likes} likes</p><a className="source-link" href={item.href} target="_blank" rel="noopener noreferrer">Original Reel ↗</a></div></article>)}</div></section><div className="related"><p className="eyebrow">Related thinking</p><TextLink href="/expertise/creative-direction">Creative direction</TextLink><TextLink href="/expertise/social-media-strategy">Social media strategy</TextLink></div><ContactCTA/><JsonLd data={{'@context':'https://schema.org','@type':'CreativeWork',name:'@sl6dl7 — A visual world for words',url:site.url+'/work/sl6dl7',creator:person,description:'A documented collection of personal creator Reels associated with Mayank Harsh and @sl6dl7.',image:site.url+work[3].image,citation:evidenceUrl}}/></PageShell>;}
